# Assignment 2

## Gabriel Santos
### '2022-21-07'

### Math Bridge Week 2 Assignment

#### Do not use built in programs to do the following.  Write the programs to demonstrate that you understand the math behind them.  Provide all solutions in an .html file. 

### Do not use built in programs to do the following.  Write the programs to demonstrate that you understand the math behind them.  Provide all solutions in an .html file. 

### 1.  Write a Python program to compute the eigenvalues and right eigenvectors of a given square array.

In [1]:
import numpy as np
m = np.mat("3 -2;1 0")
print("Original matrix:")
print("a\n", m)
w, v = np.linalg.eig(m) 
print( "Eigenvalues of the said matrix",w)
print( "Eigenvectors of the said matrix",v)

Original matrix:
a
 [[ 3 -2]
 [ 1  0]]
Eigenvalues of the said matrix [2. 1.]
Eigenvectors of the said matrix [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


### 2. Write a Python program to compute the factor of a given array by Singular Value Decomposition

In [21]:
import numpy as np

arry = np.array([[1, 2, 0, 0, 1], [1, 2, 1, 1, 3],
                [1, 4, 2, 0, 1], [1, 3, 2, 0, 1]],dtype=np.float32)
  
print("Original array:")
print(arry)
  
U, S, V = np.linalg.svd(arry, full_matrices=False)
  
print("\nFactor of the given array  by Singular Value Decomposition:")
print("\nU=", U, "\n\nS=", S, "\n\nV=", V)

Original array:
[[1. 2. 0. 0. 1.]
 [1. 2. 1. 1. 3.]
 [1. 4. 2. 0. 1.]
 [1. 3. 2. 0. 1.]]

Factor of the given array  by Singular Value Decomposition:

U= [[-3.0875298e-01 -9.3763992e-02 -9.1558415e-01  2.3997006e-01]
 [-4.8194408e-01 -8.4113747e-01  2.2036159e-01 -1.0797395e-01]
 [-6.3137066e-01  4.4360656e-01  7.7081023e-04 -6.3606894e-01]
 [-5.2323282e-01  2.9480377e-01  3.3637166e-01  7.2537732e-01]] 

S= [7.2452655 2.302727  1.0616372 0.2765876] 

V= [[-0.26849264 -0.7834875  -0.38523793 -0.06651849 -0.4015296 ]
 [-0.08532978  0.3426522   0.27605665 -0.36527884 -0.8158875 ]
 [-0.33729044 -0.35628635  0.8427046   0.20756769  0.07784496]
 [ 0.8001244  -0.37655917  0.2554084  -0.39037883  0.01936671]]


### 3. Write a Python program to compute the determinant of an array

In [20]:
import numpy as np
arry = np.array([[ 1, 2], [3, 4]])

arry = np.array([[1,2],[3,4]])
print("Original array:")
print(arry)
result =  np.linalg.det(arry)
print("Determinant")
print(result)

Original array:
[[1 2]
 [3 4]]
Determinant
-2.0000000000000004
